# start out with specifying docker-compose version
version: '3'

# 'services' is a type of container
services: 
  # name of the service
  redis-server:
     # Docker base image to use
     image: 'redis'
  node-app:
     # adding a restart policy
     restart: "no"
    # rather than use an image, we're going to use
    # the Dockerfile; so this is saying run
    # 'docker build .' which run the Dockerfile
     build: .
    # set-up a port like we would do when 
    # 'docker run -p 8080:8081'
     ports:
       # a 'dash' represents an array
       # first number is localmachine
       # second number is the container port (index.js)
       - "4001:8081"